spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sinocook?useUnicode=ture&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.sinocook.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
server:
  port: 9090